// ============================================================================
// TEACHING NOTE: why this file exists and why the package name matters
// ----------------------------------------------------------------------------
// The mutflow compiler plugin does NOT link against mutflow-core. It resolves
// the registry class purely by fully qualified name at compile time:
//
//     FqName("io.github.anschnapp.mutflow.MutationRegistry")
//     pluginContext.referenceClass(ClassId.topLevel(...))
//
// So for the Phase-0 spike we can substitute the real (JVM-only) mutflow-core
// with this hand-written native stand-in, as long as:
//   1. the package + object name match exactly, and
//   2. the signatures of check() and checkTimeout() match exactly
//      (the injected IR calls them with all six arguments).
//
// This file is THROWAWAY. Phase 2 of DESIGN-KOTLIN-NATIVE.md replaces it with
// a real multiplatform mutflow-core.
// ============================================================================
package io.github.anschnapp.mutflow

// `platform.posix.*` exposes the C POSIX API to Kotlin/Native code. This is
// generated by the built-in "cinterop" mechanism and only exists for native
// targets - there is no such package on JVM or in common code. That is the
// reason this file lives in src/linuxX64Main/ and not src/commonMain/.
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.toKString
import platform.posix.getenv

/**
 * Stubbed @MutationTarget. Same FQN as the real annotation in
 * mutflow-annotations; the IR transformer matches it via
 * `declaration.hasAnnotation(FqName("io.github.anschnapp.mutflow.MutationTarget"))`.
 * Retention BINARY (the default for Kotlin annotations is RUNTIME; BINARY is
 * what the real one uses - anything except SOURCE works, because the
 * annotation must survive into the compiled klib metadata/IR).
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class MutationTarget

/**
 * Stubbed MutationRegistry - the minimum needed to answer the spike question
 * "does the mutflow IR transformation survive the Kotlin/Native backend?".
 *
 * Behavior:
 *  - reads MUTFLOW_ACTIVE_MUTATION (format "<pointId>:<variantIndex>",
 *    e.g. "spike.Calculator_0:1") ONCE at first access
 *  - check() prints each newly discovered mutation point to stdout (this is
 *    our poor-man's replacement for the discovery.json of the real design)
 *  - check() returns the variant index if the queried point is the active
 *    one, else null (= run original code)
 *
 * Compare with the real thing in
 * mutflow-core/src/main/kotlin/io/github/anschnapp/mutflow/MutationRegistry.kt:
 * no sessions, no locking, no touch counts - per DESIGN-KOTLIN-NATIVE.md the
 * process boundary IS the session boundary on Native, so a process-global
 * activation read from the environment at startup is exactly the model we
 * want to validate.
 */
object MutationRegistry {

    // TEACHING NOTE: getenv() returns a `CPointer<ByteVar>?` - a raw C string
    // pointer - because platform.posix is a direct C binding. `.toKString()`
    // copies it into a Kotlin String. The foreign-function API is still marked
    // experimental, hence the opt-in.
    @OptIn(ExperimentalForeignApi::class)
    private val activeMutation: Pair<String, Int>? by lazy {
        val raw = getenv("MUTFLOW_ACTIVE_MUTATION")?.toKString()
        if (raw.isNullOrBlank()) {
            null
        } else {
            // pointId may itself contain dots but not ':', so split on the
            // LAST ':' to separate "<pointId>" from "<variantIndex>".
            val sep = raw.lastIndexOf(':')
            require(sep > 0) { "MUTFLOW_ACTIVE_MUTATION must look like <pointId>:<variantIndex>, got: $raw" }
            val pair = raw.substring(0, sep) to raw.substring(sep + 1).toInt()
            println("[mutflow-stub] active mutation: ${pair.first} variant ${pair.second}")
            pair
        }
    }

    // Discovery log de-duplication: check() runs on every execution of a
    // mutated expression; we only want to print each point once.
    // Plain mutableSetOf is fine here - the spike test binary is
    // single-threaded (unlike the JVM registry, which needs concurrent sets).
    private val seenPointIds = mutableSetOf<String>()

    /**
     * Signature must match mutflow-core's MutationRegistry.check() exactly -
     * the compiler-injected IR passes all six arguments positionally.
     */
    fun check(
        pointId: String,
        variantCount: Int,
        sourceLocation: String,
        originalOperator: String,
        variantOperators: String,
        occurrenceOnLine: Int = 1
    ): Int? {
        if (seenPointIds.add(pointId)) {
            println(
                "[mutflow-stub] discovered: $pointId ($sourceLocation) " +
                    "$originalOperator -> [$variantOperators] " +
                    "variants=$variantCount occurrence=$occurrenceOnLine"
            )
        }
        val active = activeMutation ?: return null
        return if (active.first == pointId) active.second else null
    }

    /**
     * Injected at the top of every loop body in @MutationTarget classes
     * (timeout detection for infinite-loop mutations). The spike has no
     * deadline concept - a no-op keeps the injected call sites happy.
     */
    fun checkTimeout() {
        // no-op in the spike
    }
}
